Vagrant.configure("2") do |config|
config.vm.box = "matjung/nodejs14"
config.vm.network "public_network", ip: "192.168.1.200"
config.vm.provision "shell", inline: <<-SHELL
 apt-get update
 apt-get upgrade
 sudo rm app
 sudo mkdir app
 cd app
 git clone https://github.com/Fabian-Ojeda/Lab5SD.git
 cd Lab5SD
 cd Server
 sudo npm i
 sudo npm i -g pm2
 pm2 start server.js
SHELL
end